spring.application.name=stok

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/stokdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=musyan200

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=Stock Control Microservice
info.app.description=Professional stock management microservice built with Spring Boot
info.app.version=1.0.0