spring.application.name=stok

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/stokdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=musyan200

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Mail configuration (Gmail SMTP example - update with your credentials)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=stockdatabase34@gmail.com
spring.mail.password=zpcg gqlg diyt gxqk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Low stock alert job configuration
app.alert.mail.to=musyan200@gmail.com
app.alert.mail.cron=0 00 17 * * *

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=Stock Control Microservice
info.app.description=Professional stock management microservice built with Spring Boot
info.app.version=1.0.0